apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "live-stream-packager.fullname" . }}-shaka
  labels:
    {{- include "live-stream-packager.labels" . | nindent 4 }}
    app.kubernetes.io/component: packager
data:
  packagerArguments: |
{{ .Values.shaka.packagerArguments | indent 4 }}
