{{- if .Values.ingress.enabled }}
{{- $full := include "live-stream-packager.fullname" . }}

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $full }}-strip-prefix
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.ingress.pathPrefix | quote }}

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $full }}
spec:
  entryPoints:
{{- range .Values.ingress.entryPoints }}
    - {{ . }}
{{- end }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`{{ .Values.ingress.pathPrefix }}`)
      kind: Rule
      middlewares:
        - name: {{ $full }}-strip-prefix
      services:
        - name: {{ $full }}
          port: {{ .Values.service.port }}
  tls:
    certResolver: {{ .Values.ingress.tls.certResolver }}
{{- end }}
