apiVersion: v1
kind: Service
metadata:
  name: {{ include "live-stream-packager.fullname" . }}
  labels:
    {{- include "live-stream-packager.labels" . | nindent 4 }}
    app.kubernetes.io/component: packager
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "live-stream-packager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: packager
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
